// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Error interface {
	IsError()
}

type TodoResult interface {
	IsTodoResult()
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

func (Todo) IsTodoResult() {}

type TodoNotFoundError struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func (TodoNotFoundError) IsError()      {}
func (TodoNotFoundError) IsTodoResult() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
